# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905600f475854dab97540cad13313b1a0e925aea4baf567f35d73f6144ad6048b0b8ba60d7313d83d6a4a82fdb3ac30581407f46c73664e8cf0687288e96cf7c

test:
  secret_key_base: 665e584360e22947d47a27a729b3a3ae6ca16c6318fd15cfcbe7ca467851ee6608033fa62cfbe5fcccea4c5b7151258348d3cc1a0ab3bc8d491d50a565d15d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
